import { defineConfig } from 'astro/config';

// Static output. Vercel auto-detects Astro and serves dist/ with zero config.
// Sitemap is generated by src/pages/sitemap.xml.ts from the same data the
// pages are built from, so it cannot drift out of sync with real routes.
export default defineConfig({
  // Canonical origin. Set PUBLIC_SITE_URL in the host's environment at launch;
  // the fallback is the Vercel hostname, which is correct only while the site
  // is still noindex.
  site: process.env.PUBLIC_SITE_URL ?? 'https://marshall-sheds.vercel.app',
  output: 'static',
  build: { format: 'directory' },
  compressHTML: true,
});
